apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tekton-operator
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: tekton-operator-{{nameNormalized}}
    spec:
      project: default
      source:
        path: dependencies/tekton-operator
        repoURL: https://github.com/konflux-ci/konflux-ci.git
        targetRevision: main
      destination:
        namespace: tekton-operator
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
