---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pvc-ns
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: temp-storage
  namespace: test-pvc-ns
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: test-pvc-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-consumer
  namespace: test-pvc-ns
spec:
  containers:
  - name: test-pvc-consumer
    image: registry:2
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
    volumeMounts:
    - name: my-volume
      mountPath: /data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: test-pvc
