---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/results/previous/v0.9.2/release.yaml
  - certificate.yaml
patches:
  - patch: |
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1no-read-only-root-fs
        value: "This deployment needs to have write permissions"
    target:
      kind: Deployment
      name: tekton-results-api
  - patch: |
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1no-read-only-root-fs
        value: "This deployment needs to have write permissions"
    target:
      kind: Deployment
      name: tekton-results-watcher
  - patch: |
      - op: add
        path: /metadata/annotations/ignore-check.kube-linter.io~1no-read-only-root-fs
        value: "This deployment needs to have write permissions"
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsGroup: 1001
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
      - op: add
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 1001
          fsGroupChangePolicy: Always
      - op: add
        path: /spec/template/spec/initContainers
        value:
          name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /opt/bitnami/postgresql"]
          securityContext:
            runAsUser: 0
    target:
      kind: StatefulSet
      name: tekton-results-postgres
