apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: cert-manager-{{nameNormalized}}
    spec:
      project: default
      source:
        path: dependencies/cert-manager
        repoURL: https://github.com/konflux-ci/konflux-ci.git
        targetRevision: main
      destination:
        namespace: cert-manager
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
